USE CONTACTBOOK;
GO

DROP TABLE phoneNumbers;
DROP TABLE addresses;
DROP TABLE contacts;
GO

CREATE TABLE contacts (
	ID INT PRIMARY KEY IDENTITY,
	fnames VARCHAR(192) NOT NULL,
	lname VARCHAR(192) NOT NULL,
	email VARCHAR(192),
	birthday DATETIME
);
GO

CREATE TABLE addresses (
	ID INT PRIMARY KEY IDENTITY,
	contactID INT NOT NULL REFERENCES contacts(ID),
	address1 VARCHAR(192) NOT NULL,
	address2 VARCHAR(192),
	city VARCHAR(192),
	state CHAR(2),
	country CHAR(2)
);
GO

CREATE TABLE phoneNumbers (
	ID INT PRIMARY KEY IDENTITY,
	contactID INT NOT NULL REFERENCES contacts(ID),
	type VARCHAR(200),
	number VARCHAR(16) NOT NULL,
);
GO